server:
  port:  8020

spring:
  application:
    #微服务名称
    name: cloud-hystrix-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/icloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka1:7001/eureka/
      #,http://eureka2:7002/eureka/
